### ISSUE TITLE
autoplay firefox

### ISSUE THREAD

**Issue by matryosha** [syleront/smotretanime-ad-skiper#1]
Автовоспроизведение звука должно быть разрешено в файрфоксе для сайта, чтобы проиграть начальный ролик иначе после 15 секунд просто остается текст "Тут реклама братан, ща уберем подожди".

**Comment by syleront** [comment]
В настройках сними галку на пункте "Не разрешать веб-сайтам автоматически воспроизводить звук", либо добавь smotretanime.ru в исключения. У меня, к слову, на 0.4.0 все работает и без этого.
![Screenshot_17](https://user-images.githubusercontent.com/17946851/55918577-332d3e00-5bfc-11e9-8707-10d1c9202fa5.png)

**Comment by matryosha** [comment]
Я к тому что мб стоит в ридми добавить, не совсем очевидно.

**Comment by syleront** [comment]
Добавил на всякий случай в FAQ, кому надо найдут.

**Comment by soredake** [comment]
@syleront у меня почему-то и после добавления сайта в исключения, и после отключения той опции всё равно только остаётся только текст "Тут реклама братан, ща уберем подожди".

**Comment by matryosha** [comment]
@soredake Можно попробовать отчистить куки или посмотреть работает ли в инкогнито. Или мб адблок

**Comment by soredake** [comment]
@syleront куки очищены, в инкогнито тоже самое, ублок для сайта отключен

**Comment by leet5** [comment]
@syleront Не работает.

> Не  удалось загрузить видео. Отключите блокировщик рекламы (в том числе юзерскрипты), 
    скорее всего он блокирует доступ к видео. Напишите на E-mail info@smotret-anime.ru если 
    проблема остается (ошибка #604).

Видимо они обфусцировали скрипт, который подгружается позже с именем: "data:text/javascript;base64,Kgz1...KTs="

В дебагере ломается на этом моменте:
```
551|  if (window[b('0x95', 'Rhzv')] && window[b('0x96', 'qr7N')][b('0x97', 'GYZf')](b('0x98', 'Rhzv'))) {
552|      gz = window[b('0x99', 'cpdY')][b('0x9a', ']tmH')](b('0x9b', 'a@md'));
553|      gz = Math[b('0x9c', 'tOd3')](dG[b('0x9d', 'oiQw')](gz, 1.3), 0x1);
554|  }
```
