### ISSUE TITLE
Реклама

### ISSUE THREAD

**Issue by Fayilver** [syleront/smotretanime-ad-skiper#7]
Они изменили показ рекламы, теперь она показывается не в начале серии, а в рандомном месте. Звука в ней нет, но реклама присутствует в каждой серии, а не один раз, как раньше.

**Comment by Katayo0** [comment]
у меня рекламы не было,но есть чёртова попрошайка,и также появляется в середине серии.

**Comment by syleront** [comment]
Fix in 0.12.0
