### ISSUE TITLE
Ну что за люди...Скрипт полетел

### ISSUE THREAD

**Issue by wooperino** [syleront/smotretanime-ad-skiper#8]
Все было ок, до сегодняшнего дня...Один особо одаренный спалил скрипт в оф группе админа смотретки на шики,опять и через пару дней скрипт накрылся.
Чувак который кинул скрипт туда, если ты это читаешь, я тебе желаю эректильную дисфункцию на пару с админом попрошайки.

**Comment by syleront** [comment]
Во-первых, раз скрипт лежит здесь, значит он для всех, а не только для тех, кто знает о его существовании. Во-вторых, те, кто занимается сайтом, давно знают о моем скрипте, и уже не раз его фиксили. И в-третьих, fix in 0.12.0
