### ISSUE TITLE
ありがと

### ISSUE THREAD

**Issue by Stamp1de** [syleront/smotretanime-ad-skiper#9]
Спасибо, о семпай! Мне кажется или за всеми блокировками даберских сайтов и давление на шикимори за онлайн просмотр дело рук анимэ-365? Мне кажется в этой войне выгоду извлекают только они...Интересно кто за ними стоит? 
Кстати, было бы здорово, если бы получилось добавить обход блокировки через другие ресурсы, например на сайте nekomori есть онлайн просмотр разных дабов и в том числе с " анимэ 365", но там плагин не обходит блокировку, возможно дело конечно в том, что я совсем ленивая жопка и использую их плагин https://chrome.google.com/webstore/detail/nekomori-ch/falogbneclkejhpplkgekcaciijgjjpm?utm_source=chrome-ntp-icon и он как-то там по своему работает.

**Comment by ShadelessFox** [comment]
🌚senpai govno jopa

**Comment by syleront** [comment]
Расширения не могут работать на внутренних страницах других расширений, это ограничение внутри самого браузера, потому он и не встраивается во внутренний плеер плагина. Смотри на сайте nerkomori, либо напрямую с самого аниме 365, ну либо с рекламой внутри плагина ¯\_(ツ)_/¯
